# .github/workflows/android-release.yml
name: Android Release Build

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main

jobs:
  build:
    name: Build APK and Distribute
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Cache node modules
        uses: actions/cache@v3
        id: npm-cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: |
          npm install

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Restore keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > android/app/release-key.jks

      - name: Setup Android keystore properties
        run: |
          cat >> android/gradle.properties <<EOF
          MYAPP_UPLOAD_STORE_FILE=release-key.jks
          MYAPP_UPLOAD_KEY_ALIAS=${{ secrets.KEY_ALIAS }}
          MYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }}
          MYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.KEY_PASSWORD }}
          EOF

      - name: Build APK
        working-directory: android
        run: ./gradlew assembleRelease

      - name: Install Firebase CLI
        run: |
          curl -sL https://firebase.tools | bash

      - name: Upload APK to Firebase App Distribution
        run: |
          ./node_modules/.bin/firebase appdistribution:distribute android/app/build/outputs/apk/release/app-release.apk \
            --app 1:953596702137:android:ca98cb80ca19f1ec1a1a68 \
            --token ${{ secrets.FIREBASE_TOKEN }} \
            --groups "internal-testers"
